### ISSUE TITLE
Memory use saving a gif

### ISSUE THREAD

**Issue by rafaqz** [JuliaIO/ImageMagick.jl#115]
I'm saving a gif of a boolean array:

```
using FileIO
cells = rand(Bool(0):Bool(1), 300, 300, 1000)
save("/tmp/test.gif", cells, fps=30)
```       

The file is about 13Mb, but the ram used is 2-3Gb! And it doesn't go back down after save finishes. Eventually it crashes julia when it runs out of memory after a few saves. `gc()` only frees a small part of the used memory.

A smaller array does not have this effect, there is some kind of tipping point where memory use increases.
                    
imagemagick version         : 7.0.7.28-1
                      
                                                 
ImageMagick                   0.5.1  
FileIO                        0.7.0

Julia Version 0.6.2                                                                 
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)                                                   
  CPU: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz                                     
  WORD_SIZE: 64                                                                     
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)                          
  LAPACK: libopenblas
  LIBM: libm                                                                        
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)

**Comment by johnnychen94** [comment]
I got similar issues on showing lena512, with 1.3GB ram used for [lena_gray_512.png](https://github.com/cszn/DnCNN/blob/master/testsets/Set12/08.png)

* Julia v0.7 + Ubuntu 16.04 + Jupyter notebook + ImageMagick v6.9.10.10
* Julia v1.0 + Ubuntu 16.04 + Jupyter notebook + ImageMagick v6.9.10.10
* Julia v1.0 + MacOS + Jupyter notebook + ImageMagick v6.9.10-4
* Julia v1.0 + MacOS + Atom Juno  + ImageMagick v6.9.10-4

**Strange** thing is that this issue seems only appears when I use the following ways to read the image

```julia
using FileIO
lena = load("Data/Set12/08.png")
```
```julia
using TestImages
lena = testimage("lena_gray_512")
```
without `;` in the end.

And the following ways just won't
```julia
using Images
lena = load("Data/Set12/08.png")
```
```julia
using Images, TestImages
lena = testimage("lena_gray_512")
```

**Comment by timholy** [comment]
I can't replicate this anymore (Julia 1.3).
