### ISSUE TITLE
OSX troubleshooting instructions contain fatal typo

### ISSUE THREAD

**Issue by damiendr** [JuliaIO/ImageMagick.jl#23]
I have been having issues with the dreaded `ERROR: no encode delegate for this image format 'MIFF'` on OSX 10.9.5. The root of the problem being as follows:
- I have imagemagick installed system-wide with homebrew (initially from bottle, later from source)
- for some reason Julia's own homebrew does not try to install it when ImageMagick.jl is installed
- but still `deps.jl` changes `MAGICK_CONFIGURE_PATH`, `MAGICK_CODER_MODULE_PATH` and `PATH` to point to items in the _non-existent_ directory `~/.julia/v0.5/Homebrew/deps/usr/Cellar/imagemagick/6.9.2-5/` that it gets from `Homebrew.prefix("imagemagick")`.
- this breaks `MagickWand` and all checked operations like reading and writing will fail, producing the above message.

It took a surprising amount of time to find the suggestion on the project's homepage (maybe add the text of the error to the homepage to help with googling the error?).

The fix worked but only after correcting an unfortunate typo:

``` julia
using Homebrew
Homebrew.rm("imagemagick")
Homebrew.update()
Homebrew.add("imagemagick")
Pkg.build("Images")
```

The last line should read `Pkg.build("ImageMagick")` otherwise the fix does not work!

I wonder why is `Pkg.add("ImageMagick")` is not triggering a julia-specific homebrew install of imagemagick?

**Comment by tkelman** [comment]
Suggested rewordings as a PR would be welcome. Many of the main contributors to this package don't use macs afaik. I think BinDeps/Homebrew may be trying to pick up a system wide imagemagick if one is present. Not sure why that doesn't work correctly.

**Comment by timholy** [comment]
The typo comes from the fact that this used to be part of the Images package, and got split out into this stand-alone package.

As @tkelman says, neither of the two main contributors to this package has a Mac. Since I can't test anything, @damiendr, it would be a huge help if you'd click on the README file and start editing it in your webbrowser, pasting in whatever error messages would have been helpful.

On the other aspect of the problem, CC @staticfloat.

**Comment by damiendr** [comment]
Thanks for the answers! Let me know if I can be of any help for testing on OSX.

**Comment by staticfloat** [comment]
@damiendr The environment variables are getting screwed up because of [these lines](https://github.com/JuliaIO/ImageMagick.jl/blob/39dd1668ed86ebc647930536f583e1add695757b/deps/build.jl#L81-L88), which get invoked due to [this line](https://github.com/JuliaIO/ImageMagick.jl/blob/39dd1668ed86ebc647930536f583e1add695757b/deps/build.jl#L89).  I'm not sure why the `onload` hook of the Homebrew provider is getting called in your case, as it seems that it shouldn't be.
