### ISSUE TITLE
Tag release v1.4.0? 

### ISSUE THREAD

**Issue by dgleich** [JuliaIO/ImageMagick.jl#237]
@timholy @ViralBShah do we want to release and tag master as v1.4.0? 

There was a failure of CI (on commit) due to reading a remote image -- it worked after re-running it -- see the most recent CI run.

**Comment by ViralBShah** [comment]
Yes, let's tag. @dgleich Will you submit the new version?

**Comment by dgleich** [comment]
Yes -- I'm assuming this package will work if I just do `@JuliaRegistrator register` on the commit. I'll run that shortly.

**Comment by ViralBShah** [comment]
I just use the registration URL on juliahub.com (the button on top): https://juliahub.com/ui/Packages, and then paste the URL and it goes through. I wonder if that bypasses the issue of membership above.

You are already a member of JuliaIO (rather than just this package), so you may need to set your membership to public.

**Comment by ViralBShah** [comment]
Registration: https://github.com/JuliaRegistries/General/pull/117437
