### ISSUE TITLE
Tag a new release of ImageMagick.jl

### ISSUE THREAD

**Issue by ViralBShah** [JuliaIO/ImageMagick.jl#48]
Do we need to tag a new release of ImageMagick.jl to make sure it has the right lower bound for Compat?

Cc @tkelman

**Comment by timholy** [comment]
Reference? (I don't know what the issue is.)

**Comment by ViralBShah** [comment]
Unfortunately, I do not have a crisp example. I could not get Jupyter to show me images on my mac, and it finally got fixed with the latest ImageMagick checkout. However, I suspect that the issue really was precompilation related.

Given that I saw a bump for the min Compat version after the latest tag of ImageMagick, it made me wonder if a new tag was needed. 

Feel free to close if this is not necessary.

**Comment by tkelman** [comment]
https://github.com/JuliaIO/ImageMagick.jl/commit/e72d4eb8b8d1808701f9514dd602fc6135e045f8 is very unlikely to need a tag, unless you had an old version of Compat loaded somehow. Most likely precompiled old versions of packages were loaded in your session, and the problem would have been caused by something other than compat.
